---
resources:
- name: resource-tutorial
  type: git
  source:
    uri: https://github.com/1kaushik1/Concourse-practice.git
    branch: master
    paths:
     - resource-tutorial/tutorials/basic/task-scripts/task_show_uname.yml
     - resource-tutorial/tutorials/basic/task-scripts/task_show_uname.sh
jobs:
- name: job-hello-world
  public: true
  plan:
  - get: resource-tutorial
  - task: hello-world-meta
    file: resource-tutorial/tutorials/basic/task-scripts/task_show_uname.yml
